In [54]:
from scipy.fft import fft, ifft
import numpy as np

def generate_circular_matrix(size=3):
    x = np.random.randn(size)
    return np.array([np.roll(x, i) for i in range(size)])

In [55]:
C = generate_circular_matrix(3)
print(C)
x = np.random.randn(3,1)
C @ x

[[ 0.61390073 -0.76087155  1.56939262]
 [ 1.56939262  0.61390073 -0.76087155]
 [-0.76087155  1.56939262  0.61390073]]


array([[ 3.90586603],
       [-0.96971151],
       [-2.12302344]])

# Notes

LINK https://web.mit.edu/18.06/www/Spring17/Circulant-Matrices.pdf


Let $C$ be a circular matrix.
Let $F$ be the Discrete Fourier Transformation Matrix defined here https://en.wikipedia.org/wiki/DFT_matrix

We have
$$Cx = F \Lambda F^{-1}x$$
$$= (x^T (F^{-1})^T \Lambda F^T)^T$$
$$= (x^T (F^{-1}) \Lambda F)^T$$
$$= (\textrm{ifft}(x^T) \Lambda F)^T$$
$$= (\textrm{ifft}(x^T) \textrm{fft}(C^{(0)}) F)^T$$
$$= (\textrm{fft}(\textrm{ifft}(x^T) \textrm{fft}(C^{(0)})))^T$$

In [105]:
def circ_mult(C,x):
    return fft(ifft(x.T)*fft(C[0])).T
circ_mult(C, x)

array([[ 3.90586603+0.j],
       [-0.96971151-0.j],
       [-2.12302344+0.j]])

In [106]:
C@x

array([[ 3.90586603],
       [-0.96971151],
       [-2.12302344]])

In [63]:
def F(n):
    return np.array([[np.exp((2*np.pi*1j/n)*j*k) for j in range(n)] for k in range(n)])

In [83]:
np.round(np.linalg.inv(F(3)) @ C @ F(3), 3)

array([[ 1.422-0.j   , -0.   +0.j   ,  0.   -0.j   ],
       [ 0.   +0.j   ,  0.21 -2.018j,  0.   +0.j   ],
       [ 0.   +0.j   , -0.   +0.j   ,  0.21 +2.018j]])

In [95]:
np.round(np.linalg.eigvals(C), 3)

array([0.21 +2.018j, 0.21 -2.018j, 1.422+0.j   ])

In [96]:
fft(C[0])

array([1.4224218 -0.j        , 0.20964019+2.01806797j,
       0.20964019-2.01806797j])

In [90]:
ifft(C)

array([[ 0.4741406 -0.j        ,  0.06988006-0.67268932j,
         0.06988006+0.67268932j],
       [ 0.4741406 -0.j        ,  0.54762601+0.39686257j,
         0.54762601-0.39686257j],
       [ 0.4741406 -0.j        , -0.61750607+0.27582675j,
        -0.61750607-0.27582675j]])

In [94]:
C @ np.linalg.inv(F(3))

array([[ 0.4741406 -8.39187753e-18j,  0.06988006+6.72689323e-01j,
         0.06988006-6.72689323e-01j],
       [ 0.4741406 -3.38271976e-16j,  0.54762601-3.96862572e-01j,
         0.54762601+3.96862572e-01j],
       [ 0.4741406 +3.46663853e-16j, -0.61750607-2.75826751e-01j,
        -0.61750607+2.75826751e-01j]])